/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package ams.data.model;
@org.apache.avro.specific.AvroGenerated
public enum AlertSeverity implements org.apache.avro.generic.GenericEnumSymbol<AlertSeverity> {
  CRITICAL, HIGH, MEDIUM, INFO  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AlertSeverity\",\"namespace\":\"ams.data.model\",\"symbols\":[\"CRITICAL\",\"HIGH\",\"MEDIUM\",\"INFO\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
