/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package ams.data.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** A structured operational alert (BOLO, SLA breach, ...) published for the notification service to fan out. dedupKey is assigned by the producer, which knows the alert's identity best. */
@org.apache.avro.specific.AvroGenerated
public class AlertEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 205866182465529068L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AlertEvent\",\"namespace\":\"ams.data.model\",\"doc\":\"A structured operational alert (BOLO, SLA breach, ...) published for the notification service to fan out. dedupKey is assigned by the producer, which knows the alert's identity best.\",\"fields\":[{\"name\":\"source\",\"type\":\"string\",\"doc\":\"e.g. BOLO, SLA\"},{\"name\":\"severity\",\"type\":{\"type\":\"enum\",\"name\":\"AlertSeverity\",\"symbols\":[\"CRITICAL\",\"HIGH\",\"MEDIUM\",\"INFO\"]}},{\"name\":\"title\",\"type\":\"string\"},{\"name\":\"message\",\"type\":\"string\"},{\"name\":\"incidentId\",\"type\":\"string\",\"doc\":\"the accident's cacheId when known\",\"default\":\"\"},{\"name\":\"dedupKey\",\"type\":\"string\",\"doc\":\"stable identity of this alert; replays with the same key are suppressed\"},{\"name\":\"timestamp\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<AlertEvent> ENCODER =
      new BinaryMessageEncoder<AlertEvent>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AlertEvent> DECODER =
      new BinaryMessageDecoder<AlertEvent>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AlertEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AlertEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AlertEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AlertEvent>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AlertEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AlertEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AlertEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AlertEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** e.g. BOLO, SLA */
  private java.lang.CharSequence source;
  private ams.data.model.AlertSeverity severity;
  private java.lang.CharSequence title;
  private java.lang.CharSequence message;
  /** the accident's cacheId when known */
  private java.lang.CharSequence incidentId;
  /** stable identity of this alert; replays with the same key are suppressed */
  private java.lang.CharSequence dedupKey;
  private java.time.Instant timestamp;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AlertEvent() {}

  /**
   * All-args constructor.
   * @param source e.g. BOLO, SLA
   * @param severity The new value for severity
   * @param title The new value for title
   * @param message The new value for message
   * @param incidentId the accident's cacheId when known
   * @param dedupKey stable identity of this alert; replays with the same key are suppressed
   * @param timestamp The new value for timestamp
   */
  public AlertEvent(java.lang.CharSequence source, ams.data.model.AlertSeverity severity, java.lang.CharSequence title, java.lang.CharSequence message, java.lang.CharSequence incidentId, java.lang.CharSequence dedupKey, java.time.Instant timestamp) {
    this.source = source;
    this.severity = severity;
    this.title = title;
    this.message = message;
    this.incidentId = incidentId;
    this.dedupKey = dedupKey;
    this.timestamp = timestamp.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return source;
    case 1: return severity;
    case 2: return title;
    case 3: return message;
    case 4: return incidentId;
    case 5: return dedupKey;
    case 6: return timestamp;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: source = (java.lang.CharSequence)value$; break;
    case 1: severity = (ams.data.model.AlertSeverity)value$; break;
    case 2: title = (java.lang.CharSequence)value$; break;
    case 3: message = (java.lang.CharSequence)value$; break;
    case 4: incidentId = (java.lang.CharSequence)value$; break;
    case 5: dedupKey = (java.lang.CharSequence)value$; break;
    case 6: timestamp = (java.time.Instant)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'source' field.
   * @return e.g. BOLO, SLA
   */
  public java.lang.CharSequence getSource() {
    return source;
  }


  /**
   * Sets the value of the 'source' field.
   * e.g. BOLO, SLA
   * @param value the value to set.
   */
  public void setSource(java.lang.CharSequence value) {
    this.source = value;
  }

  /**
   * Gets the value of the 'severity' field.
   * @return The value of the 'severity' field.
   */
  public ams.data.model.AlertSeverity getSeverity() {
    return severity;
  }


  /**
   * Sets the value of the 'severity' field.
   * @param value the value to set.
   */
  public void setSeverity(ams.data.model.AlertSeverity value) {
    this.severity = value;
  }

  /**
   * Gets the value of the 'title' field.
   * @return The value of the 'title' field.
   */
  public java.lang.CharSequence getTitle() {
    return title;
  }


  /**
   * Sets the value of the 'title' field.
   * @param value the value to set.
   */
  public void setTitle(java.lang.CharSequence value) {
    this.title = value;
  }

  /**
   * Gets the value of the 'message' field.
   * @return The value of the 'message' field.
   */
  public java.lang.CharSequence getMessage() {
    return message;
  }


  /**
   * Sets the value of the 'message' field.
   * @param value the value to set.
   */
  public void setMessage(java.lang.CharSequence value) {
    this.message = value;
  }

  /**
   * Gets the value of the 'incidentId' field.
   * @return the accident's cacheId when known
   */
  public java.lang.CharSequence getIncidentId() {
    return incidentId;
  }


  /**
   * Sets the value of the 'incidentId' field.
   * the accident's cacheId when known
   * @param value the value to set.
   */
  public void setIncidentId(java.lang.CharSequence value) {
    this.incidentId = value;
  }

  /**
   * Gets the value of the 'dedupKey' field.
   * @return stable identity of this alert; replays with the same key are suppressed
   */
  public java.lang.CharSequence getDedupKey() {
    return dedupKey;
  }


  /**
   * Sets the value of the 'dedupKey' field.
   * stable identity of this alert; replays with the same key are suppressed
   * @param value the value to set.
   */
  public void setDedupKey(java.lang.CharSequence value) {
    this.dedupKey = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public java.time.Instant getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.time.Instant value) {
    this.timestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Creates a new AlertEvent RecordBuilder.
   * @return A new AlertEvent RecordBuilder
   */
  public static ams.data.model.AlertEvent.Builder newBuilder() {
    return new ams.data.model.AlertEvent.Builder();
  }

  /**
   * Creates a new AlertEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AlertEvent RecordBuilder
   */
  public static ams.data.model.AlertEvent.Builder newBuilder(ams.data.model.AlertEvent.Builder other) {
    if (other == null) {
      return new ams.data.model.AlertEvent.Builder();
    } else {
      return new ams.data.model.AlertEvent.Builder(other);
    }
  }

  /**
   * Creates a new AlertEvent RecordBuilder by copying an existing AlertEvent instance.
   * @param other The existing instance to copy.
   * @return A new AlertEvent RecordBuilder
   */
  public static ams.data.model.AlertEvent.Builder newBuilder(ams.data.model.AlertEvent other) {
    if (other == null) {
      return new ams.data.model.AlertEvent.Builder();
    } else {
      return new ams.data.model.AlertEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for AlertEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AlertEvent>
    implements org.apache.avro.data.RecordBuilder<AlertEvent> {

    /** e.g. BOLO, SLA */
    private java.lang.CharSequence source;
    private ams.data.model.AlertSeverity severity;
    private java.lang.CharSequence title;
    private java.lang.CharSequence message;
    /** the accident's cacheId when known */
    private java.lang.CharSequence incidentId;
    /** stable identity of this alert; replays with the same key are suppressed */
    private java.lang.CharSequence dedupKey;
    private java.time.Instant timestamp;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(ams.data.model.AlertEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.source)) {
        this.source = data().deepCopy(fields()[0].schema(), other.source);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.severity)) {
        this.severity = data().deepCopy(fields()[1].schema(), other.severity);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.title)) {
        this.title = data().deepCopy(fields()[2].schema(), other.title);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.message)) {
        this.message = data().deepCopy(fields()[3].schema(), other.message);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.incidentId)) {
        this.incidentId = data().deepCopy(fields()[4].schema(), other.incidentId);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.dedupKey)) {
        this.dedupKey = data().deepCopy(fields()[5].schema(), other.dedupKey);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[6].schema(), other.timestamp);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing AlertEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(ams.data.model.AlertEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.source)) {
        this.source = data().deepCopy(fields()[0].schema(), other.source);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.severity)) {
        this.severity = data().deepCopy(fields()[1].schema(), other.severity);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.title)) {
        this.title = data().deepCopy(fields()[2].schema(), other.title);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.message)) {
        this.message = data().deepCopy(fields()[3].schema(), other.message);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.incidentId)) {
        this.incidentId = data().deepCopy(fields()[4].schema(), other.incidentId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.dedupKey)) {
        this.dedupKey = data().deepCopy(fields()[5].schema(), other.dedupKey);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[6].schema(), other.timestamp);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'source' field.
      * e.g. BOLO, SLA
      * @return The value.
      */
    public java.lang.CharSequence getSource() {
      return source;
    }


    /**
      * Sets the value of the 'source' field.
      * e.g. BOLO, SLA
      * @param value The value of 'source'.
      * @return This builder.
      */
    public ams.data.model.AlertEvent.Builder setSource(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.source = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'source' field has been set.
      * e.g. BOLO, SLA
      * @return True if the 'source' field has been set, false otherwise.
      */
    public boolean hasSource() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'source' field.
      * e.g. BOLO, SLA
      * @return This builder.
      */
    public ams.data.model.AlertEvent.Builder clearSource() {
      source = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'severity' field.
      * @return The value.
      */
    public ams.data.model.AlertSeverity getSeverity() {
      return severity;
    }


    /**
      * Sets the value of the 'severity' field.
      * @param value The value of 'severity'.
      * @return This builder.
      */
    public ams.data.model.AlertEvent.Builder setSeverity(ams.data.model.AlertSeverity value) {
      validate(fields()[1], value);
      this.severity = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'severity' field has been set.
      * @return True if the 'severity' field has been set, false otherwise.
      */
    public boolean hasSeverity() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'severity' field.
      * @return This builder.
      */
    public ams.data.model.AlertEvent.Builder clearSeverity() {
      severity = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'title' field.
      * @return The value.
      */
    public java.lang.CharSequence getTitle() {
      return title;
    }


    /**
      * Sets the value of the 'title' field.
      * @param value The value of 'title'.
      * @return This builder.
      */
    public ams.data.model.AlertEvent.Builder setTitle(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.title = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'title' field has been set.
      * @return True if the 'title' field has been set, false otherwise.
      */
    public boolean hasTitle() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'title' field.
      * @return This builder.
      */
    public ams.data.model.AlertEvent.Builder clearTitle() {
      title = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'message' field.
      * @return The value.
      */
    public java.lang.CharSequence getMessage() {
      return message;
    }


    /**
      * Sets the value of the 'message' field.
      * @param value The value of 'message'.
      * @return This builder.
      */
    public ams.data.model.AlertEvent.Builder setMessage(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.message = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'message' field has been set.
      * @return True if the 'message' field has been set, false otherwise.
      */
    public boolean hasMessage() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'message' field.
      * @return This builder.
      */
    public ams.data.model.AlertEvent.Builder clearMessage() {
      message = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'incidentId' field.
      * the accident's cacheId when known
      * @return The value.
      */
    public java.lang.CharSequence getIncidentId() {
      return incidentId;
    }


    /**
      * Sets the value of the 'incidentId' field.
      * the accident's cacheId when known
      * @param value The value of 'incidentId'.
      * @return This builder.
      */
    public ams.data.model.AlertEvent.Builder setIncidentId(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.incidentId = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'incidentId' field has been set.
      * the accident's cacheId when known
      * @return True if the 'incidentId' field has been set, false otherwise.
      */
    public boolean hasIncidentId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'incidentId' field.
      * the accident's cacheId when known
      * @return This builder.
      */
    public ams.data.model.AlertEvent.Builder clearIncidentId() {
      incidentId = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'dedupKey' field.
      * stable identity of this alert; replays with the same key are suppressed
      * @return The value.
      */
    public java.lang.CharSequence getDedupKey() {
      return dedupKey;
    }


    /**
      * Sets the value of the 'dedupKey' field.
      * stable identity of this alert; replays with the same key are suppressed
      * @param value The value of 'dedupKey'.
      * @return This builder.
      */
    public ams.data.model.AlertEvent.Builder setDedupKey(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.dedupKey = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'dedupKey' field has been set.
      * stable identity of this alert; replays with the same key are suppressed
      * @return True if the 'dedupKey' field has been set, false otherwise.
      */
    public boolean hasDedupKey() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'dedupKey' field.
      * stable identity of this alert; replays with the same key are suppressed
      * @return This builder.
      */
    public ams.data.model.AlertEvent.Builder clearDedupKey() {
      dedupKey = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public java.time.Instant getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public ams.data.model.AlertEvent.Builder setTimestamp(java.time.Instant value) {
      validate(fields()[6], value);
      this.timestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public ams.data.model.AlertEvent.Builder clearTimestamp() {
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AlertEvent build() {
      try {
        AlertEvent record = new AlertEvent();
        record.source = fieldSetFlags()[0] ? this.source : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.severity = fieldSetFlags()[1] ? this.severity : (ams.data.model.AlertSeverity) defaultValue(fields()[1]);
        record.title = fieldSetFlags()[2] ? this.title : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.message = fieldSetFlags()[3] ? this.message : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.incidentId = fieldSetFlags()[4] ? this.incidentId : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.dedupKey = fieldSetFlags()[5] ? this.dedupKey : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.timestamp = fieldSetFlags()[6] ? this.timestamp : (java.time.Instant) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AlertEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<AlertEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AlertEvent>
    READER$ = (org.apache.avro.io.DatumReader<AlertEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










