/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package ams.data.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** A reported incident enriched with context (weather at the location, district) by the enrichment-service, published to accident.events.enriched. Flattened (no shared named types) so it is an independent downstream contract. */
@org.apache.avro.specific.AvroGenerated
public class EnrichedAccidentEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8672094293588380327L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EnrichedAccidentEvent\",\"namespace\":\"ams.data.model\",\"doc\":\"A reported incident enriched with context (weather at the location, district) by the enrichment-service, published to accident.events.enriched. Flattened (no shared named types) so it is an independent downstream contract.\",\"fields\":[{\"name\":\"cacheId\",\"type\":\"string\"},{\"name\":\"type\",\"type\":\"string\"},{\"name\":\"date\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"address\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"latitude\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"longitude\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"description\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"district\",\"type\":\"string\",\"doc\":\"resolved district / area label\",\"default\":\"\"},{\"name\":\"weatherCondition\",\"type\":\"string\",\"doc\":\"e.g. clear, rain, snow, unknown\",\"default\":\"unknown\"},{\"name\":\"temperatureC\",\"type\":\"double\",\"doc\":\"-999 = unavailable\",\"default\":-999.0},{\"name\":\"precipitationMm\",\"type\":\"double\",\"doc\":\"-1 = unavailable\",\"default\":-1.0},{\"name\":\"enrichedAt\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<EnrichedAccidentEvent> ENCODER =
      new BinaryMessageEncoder<EnrichedAccidentEvent>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EnrichedAccidentEvent> DECODER =
      new BinaryMessageDecoder<EnrichedAccidentEvent>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<EnrichedAccidentEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<EnrichedAccidentEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<EnrichedAccidentEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<EnrichedAccidentEvent>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this EnrichedAccidentEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a EnrichedAccidentEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a EnrichedAccidentEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static EnrichedAccidentEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence cacheId;
  private java.lang.CharSequence type;
  private java.lang.CharSequence date;
  private java.lang.CharSequence address;
  private java.lang.CharSequence latitude;
  private java.lang.CharSequence longitude;
  private java.lang.CharSequence description;
  /** resolved district / area label */
  private java.lang.CharSequence district;
  /** e.g. clear, rain, snow, unknown */
  private java.lang.CharSequence weatherCondition;
  /** -999 = unavailable */
  private double temperatureC;
  /** -1 = unavailable */
  private double precipitationMm;
  private java.time.Instant enrichedAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EnrichedAccidentEvent() {}

  /**
   * All-args constructor.
   * @param cacheId The new value for cacheId
   * @param type The new value for type
   * @param date The new value for date
   * @param address The new value for address
   * @param latitude The new value for latitude
   * @param longitude The new value for longitude
   * @param description The new value for description
   * @param district resolved district / area label
   * @param weatherCondition e.g. clear, rain, snow, unknown
   * @param temperatureC -999 = unavailable
   * @param precipitationMm -1 = unavailable
   * @param enrichedAt The new value for enrichedAt
   */
  public EnrichedAccidentEvent(java.lang.CharSequence cacheId, java.lang.CharSequence type, java.lang.CharSequence date, java.lang.CharSequence address, java.lang.CharSequence latitude, java.lang.CharSequence longitude, java.lang.CharSequence description, java.lang.CharSequence district, java.lang.CharSequence weatherCondition, java.lang.Double temperatureC, java.lang.Double precipitationMm, java.time.Instant enrichedAt) {
    this.cacheId = cacheId;
    this.type = type;
    this.date = date;
    this.address = address;
    this.latitude = latitude;
    this.longitude = longitude;
    this.description = description;
    this.district = district;
    this.weatherCondition = weatherCondition;
    this.temperatureC = temperatureC;
    this.precipitationMm = precipitationMm;
    this.enrichedAt = enrichedAt.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return cacheId;
    case 1: return type;
    case 2: return date;
    case 3: return address;
    case 4: return latitude;
    case 5: return longitude;
    case 6: return description;
    case 7: return district;
    case 8: return weatherCondition;
    case 9: return temperatureC;
    case 10: return precipitationMm;
    case 11: return enrichedAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: cacheId = (java.lang.CharSequence)value$; break;
    case 1: type = (java.lang.CharSequence)value$; break;
    case 2: date = (java.lang.CharSequence)value$; break;
    case 3: address = (java.lang.CharSequence)value$; break;
    case 4: latitude = (java.lang.CharSequence)value$; break;
    case 5: longitude = (java.lang.CharSequence)value$; break;
    case 6: description = (java.lang.CharSequence)value$; break;
    case 7: district = (java.lang.CharSequence)value$; break;
    case 8: weatherCondition = (java.lang.CharSequence)value$; break;
    case 9: temperatureC = (java.lang.Double)value$; break;
    case 10: precipitationMm = (java.lang.Double)value$; break;
    case 11: enrichedAt = (java.time.Instant)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'cacheId' field.
   * @return The value of the 'cacheId' field.
   */
  public java.lang.CharSequence getCacheId() {
    return cacheId;
  }


  /**
   * Sets the value of the 'cacheId' field.
   * @param value the value to set.
   */
  public void setCacheId(java.lang.CharSequence value) {
    this.cacheId = value;
  }

  /**
   * Gets the value of the 'type' field.
   * @return The value of the 'type' field.
   */
  public java.lang.CharSequence getType() {
    return type;
  }


  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(java.lang.CharSequence value) {
    this.type = value;
  }

  /**
   * Gets the value of the 'date' field.
   * @return The value of the 'date' field.
   */
  public java.lang.CharSequence getDate() {
    return date;
  }


  /**
   * Sets the value of the 'date' field.
   * @param value the value to set.
   */
  public void setDate(java.lang.CharSequence value) {
    this.date = value;
  }

  /**
   * Gets the value of the 'address' field.
   * @return The value of the 'address' field.
   */
  public java.lang.CharSequence getAddress() {
    return address;
  }


  /**
   * Sets the value of the 'address' field.
   * @param value the value to set.
   */
  public void setAddress(java.lang.CharSequence value) {
    this.address = value;
  }

  /**
   * Gets the value of the 'latitude' field.
   * @return The value of the 'latitude' field.
   */
  public java.lang.CharSequence getLatitude() {
    return latitude;
  }


  /**
   * Sets the value of the 'latitude' field.
   * @param value the value to set.
   */
  public void setLatitude(java.lang.CharSequence value) {
    this.latitude = value;
  }

  /**
   * Gets the value of the 'longitude' field.
   * @return The value of the 'longitude' field.
   */
  public java.lang.CharSequence getLongitude() {
    return longitude;
  }


  /**
   * Sets the value of the 'longitude' field.
   * @param value the value to set.
   */
  public void setLongitude(java.lang.CharSequence value) {
    this.longitude = value;
  }

  /**
   * Gets the value of the 'description' field.
   * @return The value of the 'description' field.
   */
  public java.lang.CharSequence getDescription() {
    return description;
  }


  /**
   * Sets the value of the 'description' field.
   * @param value the value to set.
   */
  public void setDescription(java.lang.CharSequence value) {
    this.description = value;
  }

  /**
   * Gets the value of the 'district' field.
   * @return resolved district / area label
   */
  public java.lang.CharSequence getDistrict() {
    return district;
  }


  /**
   * Sets the value of the 'district' field.
   * resolved district / area label
   * @param value the value to set.
   */
  public void setDistrict(java.lang.CharSequence value) {
    this.district = value;
  }

  /**
   * Gets the value of the 'weatherCondition' field.
   * @return e.g. clear, rain, snow, unknown
   */
  public java.lang.CharSequence getWeatherCondition() {
    return weatherCondition;
  }


  /**
   * Sets the value of the 'weatherCondition' field.
   * e.g. clear, rain, snow, unknown
   * @param value the value to set.
   */
  public void setWeatherCondition(java.lang.CharSequence value) {
    this.weatherCondition = value;
  }

  /**
   * Gets the value of the 'temperatureC' field.
   * @return -999 = unavailable
   */
  public double getTemperatureC() {
    return temperatureC;
  }


  /**
   * Sets the value of the 'temperatureC' field.
   * -999 = unavailable
   * @param value the value to set.
   */
  public void setTemperatureC(double value) {
    this.temperatureC = value;
  }

  /**
   * Gets the value of the 'precipitationMm' field.
   * @return -1 = unavailable
   */
  public double getPrecipitationMm() {
    return precipitationMm;
  }


  /**
   * Sets the value of the 'precipitationMm' field.
   * -1 = unavailable
   * @param value the value to set.
   */
  public void setPrecipitationMm(double value) {
    this.precipitationMm = value;
  }

  /**
   * Gets the value of the 'enrichedAt' field.
   * @return The value of the 'enrichedAt' field.
   */
  public java.time.Instant getEnrichedAt() {
    return enrichedAt;
  }


  /**
   * Sets the value of the 'enrichedAt' field.
   * @param value the value to set.
   */
  public void setEnrichedAt(java.time.Instant value) {
    this.enrichedAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Creates a new EnrichedAccidentEvent RecordBuilder.
   * @return A new EnrichedAccidentEvent RecordBuilder
   */
  public static ams.data.model.EnrichedAccidentEvent.Builder newBuilder() {
    return new ams.data.model.EnrichedAccidentEvent.Builder();
  }

  /**
   * Creates a new EnrichedAccidentEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EnrichedAccidentEvent RecordBuilder
   */
  public static ams.data.model.EnrichedAccidentEvent.Builder newBuilder(ams.data.model.EnrichedAccidentEvent.Builder other) {
    if (other == null) {
      return new ams.data.model.EnrichedAccidentEvent.Builder();
    } else {
      return new ams.data.model.EnrichedAccidentEvent.Builder(other);
    }
  }

  /**
   * Creates a new EnrichedAccidentEvent RecordBuilder by copying an existing EnrichedAccidentEvent instance.
   * @param other The existing instance to copy.
   * @return A new EnrichedAccidentEvent RecordBuilder
   */
  public static ams.data.model.EnrichedAccidentEvent.Builder newBuilder(ams.data.model.EnrichedAccidentEvent other) {
    if (other == null) {
      return new ams.data.model.EnrichedAccidentEvent.Builder();
    } else {
      return new ams.data.model.EnrichedAccidentEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for EnrichedAccidentEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EnrichedAccidentEvent>
    implements org.apache.avro.data.RecordBuilder<EnrichedAccidentEvent> {

    private java.lang.CharSequence cacheId;
    private java.lang.CharSequence type;
    private java.lang.CharSequence date;
    private java.lang.CharSequence address;
    private java.lang.CharSequence latitude;
    private java.lang.CharSequence longitude;
    private java.lang.CharSequence description;
    /** resolved district / area label */
    private java.lang.CharSequence district;
    /** e.g. clear, rain, snow, unknown */
    private java.lang.CharSequence weatherCondition;
    /** -999 = unavailable */
    private double temperatureC;
    /** -1 = unavailable */
    private double precipitationMm;
    private java.time.Instant enrichedAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(ams.data.model.EnrichedAccidentEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.cacheId)) {
        this.cacheId = data().deepCopy(fields()[0].schema(), other.cacheId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.type)) {
        this.type = data().deepCopy(fields()[1].schema(), other.type);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.date)) {
        this.date = data().deepCopy(fields()[2].schema(), other.date);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.address)) {
        this.address = data().deepCopy(fields()[3].schema(), other.address);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.latitude)) {
        this.latitude = data().deepCopy(fields()[4].schema(), other.latitude);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.longitude)) {
        this.longitude = data().deepCopy(fields()[5].schema(), other.longitude);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.description)) {
        this.description = data().deepCopy(fields()[6].schema(), other.description);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.district)) {
        this.district = data().deepCopy(fields()[7].schema(), other.district);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.weatherCondition)) {
        this.weatherCondition = data().deepCopy(fields()[8].schema(), other.weatherCondition);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.temperatureC)) {
        this.temperatureC = data().deepCopy(fields()[9].schema(), other.temperatureC);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.precipitationMm)) {
        this.precipitationMm = data().deepCopy(fields()[10].schema(), other.precipitationMm);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.enrichedAt)) {
        this.enrichedAt = data().deepCopy(fields()[11].schema(), other.enrichedAt);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
    }

    /**
     * Creates a Builder by copying an existing EnrichedAccidentEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(ams.data.model.EnrichedAccidentEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.cacheId)) {
        this.cacheId = data().deepCopy(fields()[0].schema(), other.cacheId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.type)) {
        this.type = data().deepCopy(fields()[1].schema(), other.type);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.date)) {
        this.date = data().deepCopy(fields()[2].schema(), other.date);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.address)) {
        this.address = data().deepCopy(fields()[3].schema(), other.address);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.latitude)) {
        this.latitude = data().deepCopy(fields()[4].schema(), other.latitude);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.longitude)) {
        this.longitude = data().deepCopy(fields()[5].schema(), other.longitude);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.description)) {
        this.description = data().deepCopy(fields()[6].schema(), other.description);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.district)) {
        this.district = data().deepCopy(fields()[7].schema(), other.district);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.weatherCondition)) {
        this.weatherCondition = data().deepCopy(fields()[8].schema(), other.weatherCondition);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.temperatureC)) {
        this.temperatureC = data().deepCopy(fields()[9].schema(), other.temperatureC);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.precipitationMm)) {
        this.precipitationMm = data().deepCopy(fields()[10].schema(), other.precipitationMm);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.enrichedAt)) {
        this.enrichedAt = data().deepCopy(fields()[11].schema(), other.enrichedAt);
        fieldSetFlags()[11] = true;
      }
    }

    /**
      * Gets the value of the 'cacheId' field.
      * @return The value.
      */
    public java.lang.CharSequence getCacheId() {
      return cacheId;
    }


    /**
      * Sets the value of the 'cacheId' field.
      * @param value The value of 'cacheId'.
      * @return This builder.
      */
    public ams.data.model.EnrichedAccidentEvent.Builder setCacheId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.cacheId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'cacheId' field has been set.
      * @return True if the 'cacheId' field has been set, false otherwise.
      */
    public boolean hasCacheId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'cacheId' field.
      * @return This builder.
      */
    public ams.data.model.EnrichedAccidentEvent.Builder clearCacheId() {
      cacheId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'type' field.
      * @return The value.
      */
    public java.lang.CharSequence getType() {
      return type;
    }


    /**
      * Sets the value of the 'type' field.
      * @param value The value of 'type'.
      * @return This builder.
      */
    public ams.data.model.EnrichedAccidentEvent.Builder setType(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.type = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'type' field has been set.
      * @return True if the 'type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'type' field.
      * @return This builder.
      */
    public ams.data.model.EnrichedAccidentEvent.Builder clearType() {
      type = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'date' field.
      * @return The value.
      */
    public java.lang.CharSequence getDate() {
      return date;
    }


    /**
      * Sets the value of the 'date' field.
      * @param value The value of 'date'.
      * @return This builder.
      */
    public ams.data.model.EnrichedAccidentEvent.Builder setDate(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.date = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'date' field has been set.
      * @return True if the 'date' field has been set, false otherwise.
      */
    public boolean hasDate() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'date' field.
      * @return This builder.
      */
    public ams.data.model.EnrichedAccidentEvent.Builder clearDate() {
      date = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'address' field.
      * @return The value.
      */
    public java.lang.CharSequence getAddress() {
      return address;
    }


    /**
      * Sets the value of the 'address' field.
      * @param value The value of 'address'.
      * @return This builder.
      */
    public ams.data.model.EnrichedAccidentEvent.Builder setAddress(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.address = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'address' field has been set.
      * @return True if the 'address' field has been set, false otherwise.
      */
    public boolean hasAddress() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'address' field.
      * @return This builder.
      */
    public ams.data.model.EnrichedAccidentEvent.Builder clearAddress() {
      address = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'latitude' field.
      * @return The value.
      */
    public java.lang.CharSequence getLatitude() {
      return latitude;
    }


    /**
      * Sets the value of the 'latitude' field.
      * @param value The value of 'latitude'.
      * @return This builder.
      */
    public ams.data.model.EnrichedAccidentEvent.Builder setLatitude(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.latitude = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'latitude' field has been set.
      * @return True if the 'latitude' field has been set, false otherwise.
      */
    public boolean hasLatitude() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'latitude' field.
      * @return This builder.
      */
    public ams.data.model.EnrichedAccidentEvent.Builder clearLatitude() {
      latitude = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'longitude' field.
      * @return The value.
      */
    public java.lang.CharSequence getLongitude() {
      return longitude;
    }


    /**
      * Sets the value of the 'longitude' field.
      * @param value The value of 'longitude'.
      * @return This builder.
      */
    public ams.data.model.EnrichedAccidentEvent.Builder setLongitude(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.longitude = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'longitude' field has been set.
      * @return True if the 'longitude' field has been set, false otherwise.
      */
    public boolean hasLongitude() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'longitude' field.
      * @return This builder.
      */
    public ams.data.model.EnrichedAccidentEvent.Builder clearLongitude() {
      longitude = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'description' field.
      * @return The value.
      */
    public java.lang.CharSequence getDescription() {
      return description;
    }


    /**
      * Sets the value of the 'description' field.
      * @param value The value of 'description'.
      * @return This builder.
      */
    public ams.data.model.EnrichedAccidentEvent.Builder setDescription(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.description = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'description' field has been set.
      * @return True if the 'description' field has been set, false otherwise.
      */
    public boolean hasDescription() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'description' field.
      * @return This builder.
      */
    public ams.data.model.EnrichedAccidentEvent.Builder clearDescription() {
      description = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'district' field.
      * resolved district / area label
      * @return The value.
      */
    public java.lang.CharSequence getDistrict() {
      return district;
    }


    /**
      * Sets the value of the 'district' field.
      * resolved district / area label
      * @param value The value of 'district'.
      * @return This builder.
      */
    public ams.data.model.EnrichedAccidentEvent.Builder setDistrict(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.district = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'district' field has been set.
      * resolved district / area label
      * @return True if the 'district' field has been set, false otherwise.
      */
    public boolean hasDistrict() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'district' field.
      * resolved district / area label
      * @return This builder.
      */
    public ams.data.model.EnrichedAccidentEvent.Builder clearDistrict() {
      district = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'weatherCondition' field.
      * e.g. clear, rain, snow, unknown
      * @return The value.
      */
    public java.lang.CharSequence getWeatherCondition() {
      return weatherCondition;
    }


    /**
      * Sets the value of the 'weatherCondition' field.
      * e.g. clear, rain, snow, unknown
      * @param value The value of 'weatherCondition'.
      * @return This builder.
      */
    public ams.data.model.EnrichedAccidentEvent.Builder setWeatherCondition(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.weatherCondition = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'weatherCondition' field has been set.
      * e.g. clear, rain, snow, unknown
      * @return True if the 'weatherCondition' field has been set, false otherwise.
      */
    public boolean hasWeatherCondition() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'weatherCondition' field.
      * e.g. clear, rain, snow, unknown
      * @return This builder.
      */
    public ams.data.model.EnrichedAccidentEvent.Builder clearWeatherCondition() {
      weatherCondition = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'temperatureC' field.
      * -999 = unavailable
      * @return The value.
      */
    public double getTemperatureC() {
      return temperatureC;
    }


    /**
      * Sets the value of the 'temperatureC' field.
      * -999 = unavailable
      * @param value The value of 'temperatureC'.
      * @return This builder.
      */
    public ams.data.model.EnrichedAccidentEvent.Builder setTemperatureC(double value) {
      validate(fields()[9], value);
      this.temperatureC = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'temperatureC' field has been set.
      * -999 = unavailable
      * @return True if the 'temperatureC' field has been set, false otherwise.
      */
    public boolean hasTemperatureC() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'temperatureC' field.
      * -999 = unavailable
      * @return This builder.
      */
    public ams.data.model.EnrichedAccidentEvent.Builder clearTemperatureC() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'precipitationMm' field.
      * -1 = unavailable
      * @return The value.
      */
    public double getPrecipitationMm() {
      return precipitationMm;
    }


    /**
      * Sets the value of the 'precipitationMm' field.
      * -1 = unavailable
      * @param value The value of 'precipitationMm'.
      * @return This builder.
      */
    public ams.data.model.EnrichedAccidentEvent.Builder setPrecipitationMm(double value) {
      validate(fields()[10], value);
      this.precipitationMm = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'precipitationMm' field has been set.
      * -1 = unavailable
      * @return True if the 'precipitationMm' field has been set, false otherwise.
      */
    public boolean hasPrecipitationMm() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'precipitationMm' field.
      * -1 = unavailable
      * @return This builder.
      */
    public ams.data.model.EnrichedAccidentEvent.Builder clearPrecipitationMm() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'enrichedAt' field.
      * @return The value.
      */
    public java.time.Instant getEnrichedAt() {
      return enrichedAt;
    }


    /**
      * Sets the value of the 'enrichedAt' field.
      * @param value The value of 'enrichedAt'.
      * @return This builder.
      */
    public ams.data.model.EnrichedAccidentEvent.Builder setEnrichedAt(java.time.Instant value) {
      validate(fields()[11], value);
      this.enrichedAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'enrichedAt' field has been set.
      * @return True if the 'enrichedAt' field has been set, false otherwise.
      */
    public boolean hasEnrichedAt() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'enrichedAt' field.
      * @return This builder.
      */
    public ams.data.model.EnrichedAccidentEvent.Builder clearEnrichedAt() {
      fieldSetFlags()[11] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public EnrichedAccidentEvent build() {
      try {
        EnrichedAccidentEvent record = new EnrichedAccidentEvent();
        record.cacheId = fieldSetFlags()[0] ? this.cacheId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.type = fieldSetFlags()[1] ? this.type : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.date = fieldSetFlags()[2] ? this.date : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.address = fieldSetFlags()[3] ? this.address : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.latitude = fieldSetFlags()[4] ? this.latitude : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.longitude = fieldSetFlags()[5] ? this.longitude : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.description = fieldSetFlags()[6] ? this.description : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.district = fieldSetFlags()[7] ? this.district : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.weatherCondition = fieldSetFlags()[8] ? this.weatherCondition : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.temperatureC = fieldSetFlags()[9] ? this.temperatureC : (java.lang.Double) defaultValue(fields()[9]);
        record.precipitationMm = fieldSetFlags()[10] ? this.precipitationMm : (java.lang.Double) defaultValue(fields()[10]);
        record.enrichedAt = fieldSetFlags()[11] ? this.enrichedAt : (java.time.Instant) defaultValue(fields()[11]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EnrichedAccidentEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<EnrichedAccidentEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EnrichedAccidentEvent>
    READER$ = (org.apache.avro.io.DatumReader<EnrichedAccidentEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










