/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package ams.data.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Lifecycle of a CORRELATED incident (topic incident.events): many citizen reports of the same real-world event are merged into one incident by the correlation service (same accident type, ~150m grid cell, rolling time window). */
@org.apache.avro.specific.AvroGenerated
public class IncidentEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1027661082959152100L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"IncidentEvent\",\"namespace\":\"ams.data.model\",\"doc\":\"Lifecycle of a CORRELATED incident (topic incident.events): many citizen reports of the same real-world event are merged into one incident by the correlation service (same accident type, ~150m grid cell, rolling time window).\",\"fields\":[{\"name\":\"incidentId\",\"type\":\"string\"},{\"name\":\"status\",\"type\":{\"type\":\"enum\",\"name\":\"IncidentStatus\",\"symbols\":[\"OPENED\",\"UPDATED\",\"CLOSED\"]}},{\"name\":\"accidentType\",\"type\":{\"type\":\"enum\",\"name\":\"AccidentType\",\"symbols\":[\"CRIMINAL\",\"CAR_ACCIDENT\",\"OTHER_ACCIDENT\",\"FIRE_ACCIDENT\"]}},{\"name\":\"address\",\"type\":\"string\",\"doc\":\"first report's address\",\"default\":\"\"},{\"name\":\"latitude\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"longitude\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"reportCount\",\"type\":\"int\"},{\"name\":\"lastReportId\",\"type\":\"string\",\"doc\":\"cacheId of the report that caused this update\",\"default\":\"\"},{\"name\":\"timestamp\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<IncidentEvent> ENCODER =
      new BinaryMessageEncoder<IncidentEvent>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<IncidentEvent> DECODER =
      new BinaryMessageDecoder<IncidentEvent>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<IncidentEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<IncidentEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<IncidentEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<IncidentEvent>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this IncidentEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a IncidentEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a IncidentEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static IncidentEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence incidentId;
  private ams.data.model.IncidentStatus status;
  private ams.data.model.AccidentType accidentType;
  /** first report's address */
  private java.lang.CharSequence address;
  private java.lang.CharSequence latitude;
  private java.lang.CharSequence longitude;
  private int reportCount;
  /** cacheId of the report that caused this update */
  private java.lang.CharSequence lastReportId;
  private java.time.Instant timestamp;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public IncidentEvent() {}

  /**
   * All-args constructor.
   * @param incidentId The new value for incidentId
   * @param status The new value for status
   * @param accidentType The new value for accidentType
   * @param address first report's address
   * @param latitude The new value for latitude
   * @param longitude The new value for longitude
   * @param reportCount The new value for reportCount
   * @param lastReportId cacheId of the report that caused this update
   * @param timestamp The new value for timestamp
   */
  public IncidentEvent(java.lang.CharSequence incidentId, ams.data.model.IncidentStatus status, ams.data.model.AccidentType accidentType, java.lang.CharSequence address, java.lang.CharSequence latitude, java.lang.CharSequence longitude, java.lang.Integer reportCount, java.lang.CharSequence lastReportId, java.time.Instant timestamp) {
    this.incidentId = incidentId;
    this.status = status;
    this.accidentType = accidentType;
    this.address = address;
    this.latitude = latitude;
    this.longitude = longitude;
    this.reportCount = reportCount;
    this.lastReportId = lastReportId;
    this.timestamp = timestamp.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return incidentId;
    case 1: return status;
    case 2: return accidentType;
    case 3: return address;
    case 4: return latitude;
    case 5: return longitude;
    case 6: return reportCount;
    case 7: return lastReportId;
    case 8: return timestamp;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: incidentId = (java.lang.CharSequence)value$; break;
    case 1: status = (ams.data.model.IncidentStatus)value$; break;
    case 2: accidentType = (ams.data.model.AccidentType)value$; break;
    case 3: address = (java.lang.CharSequence)value$; break;
    case 4: latitude = (java.lang.CharSequence)value$; break;
    case 5: longitude = (java.lang.CharSequence)value$; break;
    case 6: reportCount = (java.lang.Integer)value$; break;
    case 7: lastReportId = (java.lang.CharSequence)value$; break;
    case 8: timestamp = (java.time.Instant)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'incidentId' field.
   * @return The value of the 'incidentId' field.
   */
  public java.lang.CharSequence getIncidentId() {
    return incidentId;
  }


  /**
   * Sets the value of the 'incidentId' field.
   * @param value the value to set.
   */
  public void setIncidentId(java.lang.CharSequence value) {
    this.incidentId = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public ams.data.model.IncidentStatus getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(ams.data.model.IncidentStatus value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'accidentType' field.
   * @return The value of the 'accidentType' field.
   */
  public ams.data.model.AccidentType getAccidentType() {
    return accidentType;
  }


  /**
   * Sets the value of the 'accidentType' field.
   * @param value the value to set.
   */
  public void setAccidentType(ams.data.model.AccidentType value) {
    this.accidentType = value;
  }

  /**
   * Gets the value of the 'address' field.
   * @return first report's address
   */
  public java.lang.CharSequence getAddress() {
    return address;
  }


  /**
   * Sets the value of the 'address' field.
   * first report's address
   * @param value the value to set.
   */
  public void setAddress(java.lang.CharSequence value) {
    this.address = value;
  }

  /**
   * Gets the value of the 'latitude' field.
   * @return The value of the 'latitude' field.
   */
  public java.lang.CharSequence getLatitude() {
    return latitude;
  }


  /**
   * Sets the value of the 'latitude' field.
   * @param value the value to set.
   */
  public void setLatitude(java.lang.CharSequence value) {
    this.latitude = value;
  }

  /**
   * Gets the value of the 'longitude' field.
   * @return The value of the 'longitude' field.
   */
  public java.lang.CharSequence getLongitude() {
    return longitude;
  }


  /**
   * Sets the value of the 'longitude' field.
   * @param value the value to set.
   */
  public void setLongitude(java.lang.CharSequence value) {
    this.longitude = value;
  }

  /**
   * Gets the value of the 'reportCount' field.
   * @return The value of the 'reportCount' field.
   */
  public int getReportCount() {
    return reportCount;
  }


  /**
   * Sets the value of the 'reportCount' field.
   * @param value the value to set.
   */
  public void setReportCount(int value) {
    this.reportCount = value;
  }

  /**
   * Gets the value of the 'lastReportId' field.
   * @return cacheId of the report that caused this update
   */
  public java.lang.CharSequence getLastReportId() {
    return lastReportId;
  }


  /**
   * Sets the value of the 'lastReportId' field.
   * cacheId of the report that caused this update
   * @param value the value to set.
   */
  public void setLastReportId(java.lang.CharSequence value) {
    this.lastReportId = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public java.time.Instant getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.time.Instant value) {
    this.timestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Creates a new IncidentEvent RecordBuilder.
   * @return A new IncidentEvent RecordBuilder
   */
  public static ams.data.model.IncidentEvent.Builder newBuilder() {
    return new ams.data.model.IncidentEvent.Builder();
  }

  /**
   * Creates a new IncidentEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new IncidentEvent RecordBuilder
   */
  public static ams.data.model.IncidentEvent.Builder newBuilder(ams.data.model.IncidentEvent.Builder other) {
    if (other == null) {
      return new ams.data.model.IncidentEvent.Builder();
    } else {
      return new ams.data.model.IncidentEvent.Builder(other);
    }
  }

  /**
   * Creates a new IncidentEvent RecordBuilder by copying an existing IncidentEvent instance.
   * @param other The existing instance to copy.
   * @return A new IncidentEvent RecordBuilder
   */
  public static ams.data.model.IncidentEvent.Builder newBuilder(ams.data.model.IncidentEvent other) {
    if (other == null) {
      return new ams.data.model.IncidentEvent.Builder();
    } else {
      return new ams.data.model.IncidentEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for IncidentEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<IncidentEvent>
    implements org.apache.avro.data.RecordBuilder<IncidentEvent> {

    private java.lang.CharSequence incidentId;
    private ams.data.model.IncidentStatus status;
    private ams.data.model.AccidentType accidentType;
    /** first report's address */
    private java.lang.CharSequence address;
    private java.lang.CharSequence latitude;
    private java.lang.CharSequence longitude;
    private int reportCount;
    /** cacheId of the report that caused this update */
    private java.lang.CharSequence lastReportId;
    private java.time.Instant timestamp;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(ams.data.model.IncidentEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.incidentId)) {
        this.incidentId = data().deepCopy(fields()[0].schema(), other.incidentId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.status)) {
        this.status = data().deepCopy(fields()[1].schema(), other.status);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.accidentType)) {
        this.accidentType = data().deepCopy(fields()[2].schema(), other.accidentType);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.address)) {
        this.address = data().deepCopy(fields()[3].schema(), other.address);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.latitude)) {
        this.latitude = data().deepCopy(fields()[4].schema(), other.latitude);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.longitude)) {
        this.longitude = data().deepCopy(fields()[5].schema(), other.longitude);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.reportCount)) {
        this.reportCount = data().deepCopy(fields()[6].schema(), other.reportCount);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.lastReportId)) {
        this.lastReportId = data().deepCopy(fields()[7].schema(), other.lastReportId);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[8].schema(), other.timestamp);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
    }

    /**
     * Creates a Builder by copying an existing IncidentEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(ams.data.model.IncidentEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.incidentId)) {
        this.incidentId = data().deepCopy(fields()[0].schema(), other.incidentId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.status)) {
        this.status = data().deepCopy(fields()[1].schema(), other.status);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.accidentType)) {
        this.accidentType = data().deepCopy(fields()[2].schema(), other.accidentType);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.address)) {
        this.address = data().deepCopy(fields()[3].schema(), other.address);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.latitude)) {
        this.latitude = data().deepCopy(fields()[4].schema(), other.latitude);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.longitude)) {
        this.longitude = data().deepCopy(fields()[5].schema(), other.longitude);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.reportCount)) {
        this.reportCount = data().deepCopy(fields()[6].schema(), other.reportCount);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.lastReportId)) {
        this.lastReportId = data().deepCopy(fields()[7].schema(), other.lastReportId);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[8].schema(), other.timestamp);
        fieldSetFlags()[8] = true;
      }
    }

    /**
      * Gets the value of the 'incidentId' field.
      * @return The value.
      */
    public java.lang.CharSequence getIncidentId() {
      return incidentId;
    }


    /**
      * Sets the value of the 'incidentId' field.
      * @param value The value of 'incidentId'.
      * @return This builder.
      */
    public ams.data.model.IncidentEvent.Builder setIncidentId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.incidentId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'incidentId' field has been set.
      * @return True if the 'incidentId' field has been set, false otherwise.
      */
    public boolean hasIncidentId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'incidentId' field.
      * @return This builder.
      */
    public ams.data.model.IncidentEvent.Builder clearIncidentId() {
      incidentId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public ams.data.model.IncidentStatus getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public ams.data.model.IncidentEvent.Builder setStatus(ams.data.model.IncidentStatus value) {
      validate(fields()[1], value);
      this.status = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public ams.data.model.IncidentEvent.Builder clearStatus() {
      status = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'accidentType' field.
      * @return The value.
      */
    public ams.data.model.AccidentType getAccidentType() {
      return accidentType;
    }


    /**
      * Sets the value of the 'accidentType' field.
      * @param value The value of 'accidentType'.
      * @return This builder.
      */
    public ams.data.model.IncidentEvent.Builder setAccidentType(ams.data.model.AccidentType value) {
      validate(fields()[2], value);
      this.accidentType = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'accidentType' field has been set.
      * @return True if the 'accidentType' field has been set, false otherwise.
      */
    public boolean hasAccidentType() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'accidentType' field.
      * @return This builder.
      */
    public ams.data.model.IncidentEvent.Builder clearAccidentType() {
      accidentType = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'address' field.
      * first report's address
      * @return The value.
      */
    public java.lang.CharSequence getAddress() {
      return address;
    }


    /**
      * Sets the value of the 'address' field.
      * first report's address
      * @param value The value of 'address'.
      * @return This builder.
      */
    public ams.data.model.IncidentEvent.Builder setAddress(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.address = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'address' field has been set.
      * first report's address
      * @return True if the 'address' field has been set, false otherwise.
      */
    public boolean hasAddress() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'address' field.
      * first report's address
      * @return This builder.
      */
    public ams.data.model.IncidentEvent.Builder clearAddress() {
      address = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'latitude' field.
      * @return The value.
      */
    public java.lang.CharSequence getLatitude() {
      return latitude;
    }


    /**
      * Sets the value of the 'latitude' field.
      * @param value The value of 'latitude'.
      * @return This builder.
      */
    public ams.data.model.IncidentEvent.Builder setLatitude(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.latitude = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'latitude' field has been set.
      * @return True if the 'latitude' field has been set, false otherwise.
      */
    public boolean hasLatitude() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'latitude' field.
      * @return This builder.
      */
    public ams.data.model.IncidentEvent.Builder clearLatitude() {
      latitude = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'longitude' field.
      * @return The value.
      */
    public java.lang.CharSequence getLongitude() {
      return longitude;
    }


    /**
      * Sets the value of the 'longitude' field.
      * @param value The value of 'longitude'.
      * @return This builder.
      */
    public ams.data.model.IncidentEvent.Builder setLongitude(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.longitude = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'longitude' field has been set.
      * @return True if the 'longitude' field has been set, false otherwise.
      */
    public boolean hasLongitude() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'longitude' field.
      * @return This builder.
      */
    public ams.data.model.IncidentEvent.Builder clearLongitude() {
      longitude = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'reportCount' field.
      * @return The value.
      */
    public int getReportCount() {
      return reportCount;
    }


    /**
      * Sets the value of the 'reportCount' field.
      * @param value The value of 'reportCount'.
      * @return This builder.
      */
    public ams.data.model.IncidentEvent.Builder setReportCount(int value) {
      validate(fields()[6], value);
      this.reportCount = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'reportCount' field has been set.
      * @return True if the 'reportCount' field has been set, false otherwise.
      */
    public boolean hasReportCount() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'reportCount' field.
      * @return This builder.
      */
    public ams.data.model.IncidentEvent.Builder clearReportCount() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastReportId' field.
      * cacheId of the report that caused this update
      * @return The value.
      */
    public java.lang.CharSequence getLastReportId() {
      return lastReportId;
    }


    /**
      * Sets the value of the 'lastReportId' field.
      * cacheId of the report that caused this update
      * @param value The value of 'lastReportId'.
      * @return This builder.
      */
    public ams.data.model.IncidentEvent.Builder setLastReportId(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.lastReportId = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'lastReportId' field has been set.
      * cacheId of the report that caused this update
      * @return True if the 'lastReportId' field has been set, false otherwise.
      */
    public boolean hasLastReportId() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'lastReportId' field.
      * cacheId of the report that caused this update
      * @return This builder.
      */
    public ams.data.model.IncidentEvent.Builder clearLastReportId() {
      lastReportId = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public java.time.Instant getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public ams.data.model.IncidentEvent.Builder setTimestamp(java.time.Instant value) {
      validate(fields()[8], value);
      this.timestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public ams.data.model.IncidentEvent.Builder clearTimestamp() {
      fieldSetFlags()[8] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public IncidentEvent build() {
      try {
        IncidentEvent record = new IncidentEvent();
        record.incidentId = fieldSetFlags()[0] ? this.incidentId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.status = fieldSetFlags()[1] ? this.status : (ams.data.model.IncidentStatus) defaultValue(fields()[1]);
        record.accidentType = fieldSetFlags()[2] ? this.accidentType : (ams.data.model.AccidentType) defaultValue(fields()[2]);
        record.address = fieldSetFlags()[3] ? this.address : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.latitude = fieldSetFlags()[4] ? this.latitude : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.longitude = fieldSetFlags()[5] ? this.longitude : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.reportCount = fieldSetFlags()[6] ? this.reportCount : (java.lang.Integer) defaultValue(fields()[6]);
        record.lastReportId = fieldSetFlags()[7] ? this.lastReportId : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.timestamp = fieldSetFlags()[8] ? this.timestamp : (java.time.Instant) defaultValue(fields()[8]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<IncidentEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<IncidentEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<IncidentEvent>
    READER$ = (org.apache.avro.io.DatumReader<IncidentEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










