/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package ams.data.model;
@org.apache.avro.specific.AvroGenerated
public enum IncidentStatus implements org.apache.avro.generic.GenericEnumSymbol<IncidentStatus> {
  OPENED, UPDATED, CLOSED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"IncidentStatus\",\"namespace\":\"ams.data.model\",\"symbols\":[\"OPENED\",\"UPDATED\",\"CLOSED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
