/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package ams.data.model;
@org.apache.avro.specific.AvroGenerated
public enum UnitDispatchStatus implements org.apache.avro.generic.GenericEnumSymbol<UnitDispatchStatus> {
  DISPATCHED, EN_ROUTE, ON_SCENE, CLEARED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"UnitDispatchStatus\",\"namespace\":\"ams.data.model\",\"symbols\":[\"DISPATCHED\",\"EN_ROUTE\",\"ON_SCENE\",\"CLEARED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
