/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package ams.data.model;
@org.apache.avro.specific.AvroGenerated
public enum UnitType implements org.apache.avro.generic.GenericEnumSymbol<UnitType> {
  POLICE_CAR, AMBULANCE, FIRE_ENGINE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"UnitType\",\"namespace\":\"ams.data.model\",\"symbols\":[\"POLICE_CAR\",\"AMBULANCE\",\"FIRE_ENGINE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
