/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package ams.data.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Lifecycle update of a response unit handling an incident (topic unit.status.events). Emitted by dispatch-service on every transition; consumed for response-time/SLA tracking. */
@org.apache.avro.specific.AvroGenerated
public class UnitStatusEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6284194979808638343L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UnitStatusEvent\",\"namespace\":\"ams.data.model\",\"doc\":\"Lifecycle update of a response unit handling an incident (topic unit.status.events). Emitted by dispatch-service on every transition; consumed for response-time/SLA tracking.\",\"fields\":[{\"name\":\"dispatchId\",\"type\":\"string\",\"doc\":\"unique id of this dispatch\"},{\"name\":\"incidentId\",\"type\":\"string\",\"doc\":\"the accident's cacheId (business identity)\"},{\"name\":\"unitId\",\"type\":\"string\",\"doc\":\"e.g. AMB-2, POL-1, FIRE-3\"},{\"name\":\"unitType\",\"type\":{\"type\":\"enum\",\"name\":\"UnitType\",\"symbols\":[\"POLICE_CAR\",\"AMBULANCE\",\"FIRE_ENGINE\"]}},{\"name\":\"status\",\"type\":{\"type\":\"enum\",\"name\":\"UnitDispatchStatus\",\"symbols\":[\"DISPATCHED\",\"EN_ROUTE\",\"ON_SCENE\",\"CLEARED\"]}},{\"name\":\"latitude\",\"type\":\"string\",\"doc\":\"incident latitude\",\"default\":\"\"},{\"name\":\"longitude\",\"type\":\"string\",\"doc\":\"incident longitude\",\"default\":\"\"},{\"name\":\"timestamp\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},\"doc\":\"when the transition happened\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<UnitStatusEvent> ENCODER =
      new BinaryMessageEncoder<UnitStatusEvent>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<UnitStatusEvent> DECODER =
      new BinaryMessageDecoder<UnitStatusEvent>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<UnitStatusEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<UnitStatusEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<UnitStatusEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<UnitStatusEvent>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this UnitStatusEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a UnitStatusEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a UnitStatusEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static UnitStatusEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** unique id of this dispatch */
  private java.lang.CharSequence dispatchId;
  /** the accident's cacheId (business identity) */
  private java.lang.CharSequence incidentId;
  /** e.g. AMB-2, POL-1, FIRE-3 */
  private java.lang.CharSequence unitId;
  private ams.data.model.UnitType unitType;
  private ams.data.model.UnitDispatchStatus status;
  /** incident latitude */
  private java.lang.CharSequence latitude;
  /** incident longitude */
  private java.lang.CharSequence longitude;
  /** when the transition happened */
  private java.time.Instant timestamp;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public UnitStatusEvent() {}

  /**
   * All-args constructor.
   * @param dispatchId unique id of this dispatch
   * @param incidentId the accident's cacheId (business identity)
   * @param unitId e.g. AMB-2, POL-1, FIRE-3
   * @param unitType The new value for unitType
   * @param status The new value for status
   * @param latitude incident latitude
   * @param longitude incident longitude
   * @param timestamp when the transition happened
   */
  public UnitStatusEvent(java.lang.CharSequence dispatchId, java.lang.CharSequence incidentId, java.lang.CharSequence unitId, ams.data.model.UnitType unitType, ams.data.model.UnitDispatchStatus status, java.lang.CharSequence latitude, java.lang.CharSequence longitude, java.time.Instant timestamp) {
    this.dispatchId = dispatchId;
    this.incidentId = incidentId;
    this.unitId = unitId;
    this.unitType = unitType;
    this.status = status;
    this.latitude = latitude;
    this.longitude = longitude;
    this.timestamp = timestamp.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return dispatchId;
    case 1: return incidentId;
    case 2: return unitId;
    case 3: return unitType;
    case 4: return status;
    case 5: return latitude;
    case 6: return longitude;
    case 7: return timestamp;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: dispatchId = (java.lang.CharSequence)value$; break;
    case 1: incidentId = (java.lang.CharSequence)value$; break;
    case 2: unitId = (java.lang.CharSequence)value$; break;
    case 3: unitType = (ams.data.model.UnitType)value$; break;
    case 4: status = (ams.data.model.UnitDispatchStatus)value$; break;
    case 5: latitude = (java.lang.CharSequence)value$; break;
    case 6: longitude = (java.lang.CharSequence)value$; break;
    case 7: timestamp = (java.time.Instant)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'dispatchId' field.
   * @return unique id of this dispatch
   */
  public java.lang.CharSequence getDispatchId() {
    return dispatchId;
  }


  /**
   * Sets the value of the 'dispatchId' field.
   * unique id of this dispatch
   * @param value the value to set.
   */
  public void setDispatchId(java.lang.CharSequence value) {
    this.dispatchId = value;
  }

  /**
   * Gets the value of the 'incidentId' field.
   * @return the accident's cacheId (business identity)
   */
  public java.lang.CharSequence getIncidentId() {
    return incidentId;
  }


  /**
   * Sets the value of the 'incidentId' field.
   * the accident's cacheId (business identity)
   * @param value the value to set.
   */
  public void setIncidentId(java.lang.CharSequence value) {
    this.incidentId = value;
  }

  /**
   * Gets the value of the 'unitId' field.
   * @return e.g. AMB-2, POL-1, FIRE-3
   */
  public java.lang.CharSequence getUnitId() {
    return unitId;
  }


  /**
   * Sets the value of the 'unitId' field.
   * e.g. AMB-2, POL-1, FIRE-3
   * @param value the value to set.
   */
  public void setUnitId(java.lang.CharSequence value) {
    this.unitId = value;
  }

  /**
   * Gets the value of the 'unitType' field.
   * @return The value of the 'unitType' field.
   */
  public ams.data.model.UnitType getUnitType() {
    return unitType;
  }


  /**
   * Sets the value of the 'unitType' field.
   * @param value the value to set.
   */
  public void setUnitType(ams.data.model.UnitType value) {
    this.unitType = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public ams.data.model.UnitDispatchStatus getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(ams.data.model.UnitDispatchStatus value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'latitude' field.
   * @return incident latitude
   */
  public java.lang.CharSequence getLatitude() {
    return latitude;
  }


  /**
   * Sets the value of the 'latitude' field.
   * incident latitude
   * @param value the value to set.
   */
  public void setLatitude(java.lang.CharSequence value) {
    this.latitude = value;
  }

  /**
   * Gets the value of the 'longitude' field.
   * @return incident longitude
   */
  public java.lang.CharSequence getLongitude() {
    return longitude;
  }


  /**
   * Sets the value of the 'longitude' field.
   * incident longitude
   * @param value the value to set.
   */
  public void setLongitude(java.lang.CharSequence value) {
    this.longitude = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return when the transition happened
   */
  public java.time.Instant getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * when the transition happened
   * @param value the value to set.
   */
  public void setTimestamp(java.time.Instant value) {
    this.timestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Creates a new UnitStatusEvent RecordBuilder.
   * @return A new UnitStatusEvent RecordBuilder
   */
  public static ams.data.model.UnitStatusEvent.Builder newBuilder() {
    return new ams.data.model.UnitStatusEvent.Builder();
  }

  /**
   * Creates a new UnitStatusEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new UnitStatusEvent RecordBuilder
   */
  public static ams.data.model.UnitStatusEvent.Builder newBuilder(ams.data.model.UnitStatusEvent.Builder other) {
    if (other == null) {
      return new ams.data.model.UnitStatusEvent.Builder();
    } else {
      return new ams.data.model.UnitStatusEvent.Builder(other);
    }
  }

  /**
   * Creates a new UnitStatusEvent RecordBuilder by copying an existing UnitStatusEvent instance.
   * @param other The existing instance to copy.
   * @return A new UnitStatusEvent RecordBuilder
   */
  public static ams.data.model.UnitStatusEvent.Builder newBuilder(ams.data.model.UnitStatusEvent other) {
    if (other == null) {
      return new ams.data.model.UnitStatusEvent.Builder();
    } else {
      return new ams.data.model.UnitStatusEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for UnitStatusEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UnitStatusEvent>
    implements org.apache.avro.data.RecordBuilder<UnitStatusEvent> {

    /** unique id of this dispatch */
    private java.lang.CharSequence dispatchId;
    /** the accident's cacheId (business identity) */
    private java.lang.CharSequence incidentId;
    /** e.g. AMB-2, POL-1, FIRE-3 */
    private java.lang.CharSequence unitId;
    private ams.data.model.UnitType unitType;
    private ams.data.model.UnitDispatchStatus status;
    /** incident latitude */
    private java.lang.CharSequence latitude;
    /** incident longitude */
    private java.lang.CharSequence longitude;
    /** when the transition happened */
    private java.time.Instant timestamp;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(ams.data.model.UnitStatusEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.dispatchId)) {
        this.dispatchId = data().deepCopy(fields()[0].schema(), other.dispatchId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.incidentId)) {
        this.incidentId = data().deepCopy(fields()[1].schema(), other.incidentId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.unitId)) {
        this.unitId = data().deepCopy(fields()[2].schema(), other.unitId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.unitType)) {
        this.unitType = data().deepCopy(fields()[3].schema(), other.unitType);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.status)) {
        this.status = data().deepCopy(fields()[4].schema(), other.status);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.latitude)) {
        this.latitude = data().deepCopy(fields()[5].schema(), other.latitude);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.longitude)) {
        this.longitude = data().deepCopy(fields()[6].schema(), other.longitude);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[7].schema(), other.timestamp);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
    }

    /**
     * Creates a Builder by copying an existing UnitStatusEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(ams.data.model.UnitStatusEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.dispatchId)) {
        this.dispatchId = data().deepCopy(fields()[0].schema(), other.dispatchId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.incidentId)) {
        this.incidentId = data().deepCopy(fields()[1].schema(), other.incidentId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.unitId)) {
        this.unitId = data().deepCopy(fields()[2].schema(), other.unitId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.unitType)) {
        this.unitType = data().deepCopy(fields()[3].schema(), other.unitType);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.status)) {
        this.status = data().deepCopy(fields()[4].schema(), other.status);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.latitude)) {
        this.latitude = data().deepCopy(fields()[5].schema(), other.latitude);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.longitude)) {
        this.longitude = data().deepCopy(fields()[6].schema(), other.longitude);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[7].schema(), other.timestamp);
        fieldSetFlags()[7] = true;
      }
    }

    /**
      * Gets the value of the 'dispatchId' field.
      * unique id of this dispatch
      * @return The value.
      */
    public java.lang.CharSequence getDispatchId() {
      return dispatchId;
    }


    /**
      * Sets the value of the 'dispatchId' field.
      * unique id of this dispatch
      * @param value The value of 'dispatchId'.
      * @return This builder.
      */
    public ams.data.model.UnitStatusEvent.Builder setDispatchId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.dispatchId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'dispatchId' field has been set.
      * unique id of this dispatch
      * @return True if the 'dispatchId' field has been set, false otherwise.
      */
    public boolean hasDispatchId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'dispatchId' field.
      * unique id of this dispatch
      * @return This builder.
      */
    public ams.data.model.UnitStatusEvent.Builder clearDispatchId() {
      dispatchId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'incidentId' field.
      * the accident's cacheId (business identity)
      * @return The value.
      */
    public java.lang.CharSequence getIncidentId() {
      return incidentId;
    }


    /**
      * Sets the value of the 'incidentId' field.
      * the accident's cacheId (business identity)
      * @param value The value of 'incidentId'.
      * @return This builder.
      */
    public ams.data.model.UnitStatusEvent.Builder setIncidentId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.incidentId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'incidentId' field has been set.
      * the accident's cacheId (business identity)
      * @return True if the 'incidentId' field has been set, false otherwise.
      */
    public boolean hasIncidentId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'incidentId' field.
      * the accident's cacheId (business identity)
      * @return This builder.
      */
    public ams.data.model.UnitStatusEvent.Builder clearIncidentId() {
      incidentId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'unitId' field.
      * e.g. AMB-2, POL-1, FIRE-3
      * @return The value.
      */
    public java.lang.CharSequence getUnitId() {
      return unitId;
    }


    /**
      * Sets the value of the 'unitId' field.
      * e.g. AMB-2, POL-1, FIRE-3
      * @param value The value of 'unitId'.
      * @return This builder.
      */
    public ams.data.model.UnitStatusEvent.Builder setUnitId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.unitId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'unitId' field has been set.
      * e.g. AMB-2, POL-1, FIRE-3
      * @return True if the 'unitId' field has been set, false otherwise.
      */
    public boolean hasUnitId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'unitId' field.
      * e.g. AMB-2, POL-1, FIRE-3
      * @return This builder.
      */
    public ams.data.model.UnitStatusEvent.Builder clearUnitId() {
      unitId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'unitType' field.
      * @return The value.
      */
    public ams.data.model.UnitType getUnitType() {
      return unitType;
    }


    /**
      * Sets the value of the 'unitType' field.
      * @param value The value of 'unitType'.
      * @return This builder.
      */
    public ams.data.model.UnitStatusEvent.Builder setUnitType(ams.data.model.UnitType value) {
      validate(fields()[3], value);
      this.unitType = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'unitType' field has been set.
      * @return True if the 'unitType' field has been set, false otherwise.
      */
    public boolean hasUnitType() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'unitType' field.
      * @return This builder.
      */
    public ams.data.model.UnitStatusEvent.Builder clearUnitType() {
      unitType = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public ams.data.model.UnitDispatchStatus getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public ams.data.model.UnitStatusEvent.Builder setStatus(ams.data.model.UnitDispatchStatus value) {
      validate(fields()[4], value);
      this.status = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public ams.data.model.UnitStatusEvent.Builder clearStatus() {
      status = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'latitude' field.
      * incident latitude
      * @return The value.
      */
    public java.lang.CharSequence getLatitude() {
      return latitude;
    }


    /**
      * Sets the value of the 'latitude' field.
      * incident latitude
      * @param value The value of 'latitude'.
      * @return This builder.
      */
    public ams.data.model.UnitStatusEvent.Builder setLatitude(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.latitude = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'latitude' field has been set.
      * incident latitude
      * @return True if the 'latitude' field has been set, false otherwise.
      */
    public boolean hasLatitude() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'latitude' field.
      * incident latitude
      * @return This builder.
      */
    public ams.data.model.UnitStatusEvent.Builder clearLatitude() {
      latitude = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'longitude' field.
      * incident longitude
      * @return The value.
      */
    public java.lang.CharSequence getLongitude() {
      return longitude;
    }


    /**
      * Sets the value of the 'longitude' field.
      * incident longitude
      * @param value The value of 'longitude'.
      * @return This builder.
      */
    public ams.data.model.UnitStatusEvent.Builder setLongitude(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.longitude = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'longitude' field has been set.
      * incident longitude
      * @return True if the 'longitude' field has been set, false otherwise.
      */
    public boolean hasLongitude() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'longitude' field.
      * incident longitude
      * @return This builder.
      */
    public ams.data.model.UnitStatusEvent.Builder clearLongitude() {
      longitude = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * when the transition happened
      * @return The value.
      */
    public java.time.Instant getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * when the transition happened
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public ams.data.model.UnitStatusEvent.Builder setTimestamp(java.time.Instant value) {
      validate(fields()[7], value);
      this.timestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * when the transition happened
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * when the transition happened
      * @return This builder.
      */
    public ams.data.model.UnitStatusEvent.Builder clearTimestamp() {
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public UnitStatusEvent build() {
      try {
        UnitStatusEvent record = new UnitStatusEvent();
        record.dispatchId = fieldSetFlags()[0] ? this.dispatchId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.incidentId = fieldSetFlags()[1] ? this.incidentId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.unitId = fieldSetFlags()[2] ? this.unitId : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.unitType = fieldSetFlags()[3] ? this.unitType : (ams.data.model.UnitType) defaultValue(fields()[3]);
        record.status = fieldSetFlags()[4] ? this.status : (ams.data.model.UnitDispatchStatus) defaultValue(fields()[4]);
        record.latitude = fieldSetFlags()[5] ? this.latitude : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.longitude = fieldSetFlags()[6] ? this.longitude : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.timestamp = fieldSetFlags()[7] ? this.timestamp : (java.time.Instant) defaultValue(fields()[7]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<UnitStatusEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<UnitStatusEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<UnitStatusEvent>
    READER$ = (org.apache.avro.io.DatumReader<UnitStatusEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










